[bastion]

env = "development"
master_key_file = "/tmp/.ssh/id_rsa"
authorized_keys_file = "/tmp/.ssh/authorized_keys"

[db]

url = "root@tcp(localhost:3306)/bastion?parseTime=true"

[redis]

url = "redis://localhost:6379/1"

[web]

domain = "localhost"
host = "localhost"
port = 5566

[sshd]

host = "0.0.0.0"
port = 2222
host_key_file = "/tmp/host_rsa"

[sandbox]

image = "pagodatech/sandbox"
data_dir = "/tmp/bastion/sandboxes"
